gateways:
    local:
        connection:
            type: duckdb
            catalogs:
                postgres_demo_sales_data: "../seeds_for_local/demo_data.db"
                sales: sales.db
        state_connection:
            type: duckdb
            catalogs:
                upstream_state: state.db
    combined:
        connection:
            type: duckdb
            catalogs:
                postgres_demo_sales_data: seeds_for_local/demo_data.db
                sales: sales_combined.db
        state_connection:
            type: duckdb
            catalogs:
                upstream_state: state_combined.db
    db_notebook:
        connection:
            type: databricks
            catalog: sales
            concurrent_tasks: 4
            access_token: {{ env_var('DATABRICKS_ACCESS_TOKEN') }}
            server_hostname: {{ env_var('DATABRICKS_SERVER_HOSTNAME') }}
            http_path: {{ env_var('DATABRICKS_HTTP_PATH') }}
        state_schema: sqlmesh_upstream
        state_connection:
            type: postgres
            database: sqlmesh_state
            host: {{ env_var('POSTGRES_HOST', 'a')}}
            port: {{ env_var('POSTGRES_PORT', 1)}}
            user: {{ env_var('POSTGRES_USER', 'a')}}
            password: {{ env_var('POSTGRES_PASSWORD', 'a')}}

default_gateway: combined

model_defaults:
    dialect: databricks
    cron: "*/5 * * * *"
    start: 2024-04-01