gateways:
    local:
        connection:
            type: duckdb
            catalogs:
                sales: "../upstream/sales.db"
        state_connection:
            type: duckdb
            catalogs:
                upstream_state: state.db
    db_notebook:
        connection:
            type: databricks
            catalog: sales
            concurrent_tasks: 4
            access_token: "a_token"
            server_hostname: "a_host"
            http_path: "a_path"
        state_connection:
            type: postgres
            database: sqlmesh_state
            state_schema: sqlmesh_downstream
            host: {{ env_var('POSTGRES_HOST', 'a')}}
            port: {{ env_var('POSTGRES_PORT', 1)}}
            user: {{ env_var('POSTGRES_USER', 'a')}}
            password: {{ env_var('POSTGRES_PASSWORD', 'a')}}

default_gateway: local

model_defaults:
    dialect: databricks
    cron: "@daily"