- name: '`sales`.`bronze`.`item_info`'
  columns:
    item_id: INT
    item_name: STRING
    item_description: STRING
    price: DOUBLE
- name: '`sales`.`bronze`.`transactions`'
  columns:
    transaction_id: INT
    item_id: INT
    quantity: INT
    transaction_date: STRING
    total_price: DOUBLE
